/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package githubgreeter;

public class GitHubGreeter {

  public String welcome(String name){
  //add some code here

  }

public String wishes(){

  //add some code here
  }

}
